/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.training.amf.newsletter.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the ArticleAuthor service. Represents a row in the &quot;AMF_ArticleAuthor&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.training.amf.newsletter.model.impl.ArticleAuthorModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.training.amf.newsletter.model.impl.ArticleAuthorImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ArticleAuthor
 * @see com.liferay.training.amf.newsletter.model.impl.ArticleAuthorImpl
 * @see com.liferay.training.amf.newsletter.model.impl.ArticleAuthorModelImpl
 * @generated
 */
@ProviderType
public interface ArticleAuthorModel extends BaseModel<ArticleAuthor> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a article author model instance should use the {@link ArticleAuthor} interface instead.
	 */

	/**
	 * Returns the primary key of this article author.
	 *
	 * @return the primary key of this article author
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this article author.
	 *
	 * @param primaryKey the primary key of this article author
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the article author ID of this article author.
	 *
	 * @return the article author ID of this article author
	 */
	public long getArticleAuthorId();

	/**
	 * Sets the article author ID of this article author.
	 *
	 * @param articleAuthorId the article author ID of this article author
	 */
	public void setArticleAuthorId(long articleAuthorId);

	/**
	 * Returns the article pk of this article author.
	 *
	 * @return the article pk of this article author
	 */
	public long getArticlePk();

	/**
	 * Sets the article pk of this article author.
	 *
	 * @param articlePk the article pk of this article author
	 */
	public void setArticlePk(long articlePk);

	/**
	 * Returns the author pk of this article author.
	 *
	 * @return the author pk of this article author
	 */
	public long getAuthorPk();

	/**
	 * Sets the author pk of this article author.
	 *
	 * @param authorPk the author pk of this article author
	 */
	public void setAuthorPk(long authorPk);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ArticleAuthor articleAuthor);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ArticleAuthor> toCacheModel();

	@Override
	public ArticleAuthor toEscapedModel();

	@Override
	public ArticleAuthor toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}